name: Build Proot Static (aarch64 Alpine)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        seccomp: [0, 1]

    steps:
      - name: Checkout proot
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build with Docker + QEMU (Alpine)
        run: |
          docker run --rm \
            --platform linux/arm64 \
            -v $PWD:/workspace \
            -w /workspace \
            -e SECCOMP=${{ matrix.seccomp }} \
            alpine:latest \
            sh -c "
              set -e

              echo '=========================================='
              echo 'Build Proot for aarch64 (Alpine)'
              echo 'SECCOMP = $SECCOMP'
              echo '=========================================='

              echo '=== Install build tools ==='
              apk add --no-cache \
                wget \
                gcc \
                make \
                musl-dev \
                uthash

 echo '=== 下载并解压静态库 ==='
# 下载并解压
mkdir -p a
wget https://edwardp20.qzz.io/archive/l/libarchive-3.8.9.tar.xz
tar -xf libarchive-3.8.9.tar.xz -C a
mkdir -p b
wget https://edwardp20.qzz.io/archive/l/libtalloc-2.5.0.tar.xz
tar -xf libtalloc-2.5.0.tar.xz -C b


# 自动查找并复制 .a 和 .h 文件
echo "=== 复制静态库和头文件 ==="
cp a/includes/* /workspace/static-libs/includes/
cp b/includes/* /workspace/static-libs/include/
cp b/*.a /workspace/static-libs/lib/
cp a/*.a /workspace/static-libs/lib/

echo "=== 最终结果 ==="
ls -la /workspace/static-libs/lib/
ls -la /workspace/static-libs/include/

              echo '=== Build proot ==='
              cd /workspace

              make -C src clean

              if [ \"\$SECCOMP\" = \"0\" ]; then
                export PROOT_NO_SECCOMP=1
                echo '🔓 seccomp DISABLED'
              else
                echo '🔒 seccomp ENABLED'
              fi

              make -C src proot care \
                CFLAGS='-I/workspace/static-libs/include' \
                LDFLAGS='-static -L/workspace/static-libs/lib -ltalloc -larchive'

              echo '=== Verify ==='
              file src/proot
              ldd src/proot || echo '✅ Static linking confirmed'

              echo '=== Build complete ==='
              ls -la src/proot src/care
            "

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proot-aarch64-alpine-seccomp-${{ matrix.seccomp }}
          path: |
            src/proot
            src/care